### PR TITLE
Refactor Settings & Store templates for v1

### PR DESCRIPTION
**Pull request by barrymcgee**
## Done
- Refactored templates to use Vanilla v1 styles
- Swapped out Ubuntu logos to use dark version in designs
- Added active nav border-bottom
- Added overlay cursor to Settings menu
- Removed redundant p-footer override
## QA
- Pull down code
- Re-run snapweb build
- View locally and cross ref with designs

**Note:** This is a first pass and so structure should reflect rough outline of designs. Second pass will finesse.

Store mob: https://github.com/CanonicalLtd/snapweb-design/blob/master/Store/320px/03-snappy-store-card-mobile-320-v3.png

Store desktop: https://github.com/CanonicalLtd/snapweb-design/blob/master/Store/1440px/05-snappy-store-list-1440-card-view-v6.png
## 

Settings Mob: https://github.com/CanonicalLtd/snapweb-design/blob/master/Settings/320px/02-snappy-settings-device-info-320.png

Settings desktop: https://raw.githubusercontent.com/CanonicalLtd/snapweb-design/master/Settings/1440px/00a-snappy-settings-devices-1440.png?token=AAe24rxCY3iG4DvxMKN8FMKxsDmnlvwfks5YExHYwA%3D%3D

### CODE REVIEW

**Comment by nottrobin** [comment]
Settings tab doesn't show "active" indicator:

settings tab

**Comment by nottrobin** [comment]
In the store list view, if you click on an item, you go to the item details page. But there's no "hand" cursor to indicate that clicking is going to do anything.

Also, when you get to the item details page, there's no "back to search results" which I would expect to see.

**Comment by nottrobin** [comment]
In the settings mobile view, the buttons seem a bit too close together, even for a rough pass:

buttons close

**Comment by barrymcgee** [comment]
@nottrobin 

- Fixed active link on settings
- Fixed link cursor on snap cards
- 'Back to search results' is not on designs, will raise with Karl
- Stacked buttons is also on list to raise with Karl

**Comment by nottrobin** [comment]
The following things now seem to be broken:

- Search box doesn't work
- Clicking on items in list view no longer shows the details page (does nothing)
- Installed items in the store still say "install"

**Comment by barrymcgee** [comment]
@nottrobin Search and Store click-through are both addressed in https://github.com/barrymcgee/snapweb/pull/4 which is a separate branch created from this branch.

Installed snaps behave as expected for me: https://www.dropbox.com/s/7ulqxhawmmfyed6/Screenshot%202016-10-28%2016.58.51.png?dl=0

Perhaps it's nuances when viewed locally? I think it would be best to merge this and test on demo site? Once we have these two PR's merged, we can revert to a traditional workflow of creating an issue per bug and working through them from there.

**Comment by nottrobin** [comment]
@barrymcgee that image doesn't show anything about installed snaps. `snapweb` is clearly a special case, but if you were to install any other snap, let it finish, and then look for it in the store, you would see it still says "install", and if you click the "install" button, it briefly flickers and then goes back to saying "install".

But yeah I'm happy to treat that one as a separate issue - could you create one? I don't seem to be able to either on your fork or on the core repository...

Once we've got that issue logged, I'm happy to merge this one. But please don't merge the other one until I've taken a look.

**Comment by barrymcgee** [comment]
Have emailed re: Issues on Github. DB is on holidays until Nov 2nd. In the meantime, I've tracked this issue on our web team Trello board: https://trello.com/c/DeLggCpc

**Pull request merged**
